name: Flask Deploy EC2 Server

on: workflow_dispatch

jobs:
    Flask_deploy:
        runs-on: self-hosted
        env:
            DOCKER_USER: ${{ vars.DOCKER_USERNAME }}
        steps:
            - name: code check
              uses: actions/checkout@v5

            - name: Set the docker compose
              uses: docker/setup-compose-action@v2

            - name: deploy with Docker compose
              run: |
                  docker compose down
                  docker compose pull
                  docker compose up -d --build
