name: Run Real Tests in CI

on: workflow_dispatch

jobs:
  Run_CI:
   runs-on: ubuntu-latest
   steps:
     - name: code check
       uses: actions/checkout@v5

  test:
   runs-on: ubuntu-latest
   needs: Run_CI
   steps:
     - name: code verify
       uses:  actions/checkout@v5
     
     - name: pipe line stop the code (use exit 0)/ success the pipe line exit 0 
       run: exit 0
       
     - name: run the shell script
       run: |
        echo "My secript is running"
        chmod +x newshellscrit.sh
        ./newshellscrit.sh
