name: deploy the image to self-hosted

on: workflow_dispatch

jobs:
  CD_deploy:
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    runs-on: self-hosted

    steps:
      - name: code check
        uses: actions/checkout@v4

      - name: deploy with Docker Compose
        run: docker compose up -d --build
