name: Docker Publish

on:
 push:
   branches:
     - main


jobs:
 build_image:   
   runs-on: ubuntu-latest
   steps:
     - name: Check the repo code
       uses: actions/checkout@v5

     - name: Docker build the image
       run: docker build -t mygithubimage .

     - name: docker run
       run: docker run -d -p 5050:80 --name myci mygithubimage
     - name: check the images
       run: docker images

     - name: docker check running container
       run: docker ps

     - name: check the log
       run: docker logs myci

      
