name: Docker build and Push to Docker Hub

on: workflow_dispatch

jobs:
  docker_build:
   runs-on: ubuntu-latest
   steps:
     - name: code check
       uses: actions/checkout@v5

     - name: docker login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ vars.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

     - name: Build and Push to Docker Hub
       uses: docker/build-push-action@v6
       with:
         context: .
         file: ./lintDocker
         push: true
         tags: |
          ${{ vars.DOCKER_USERNAME }}/github-actions-app:${{ github.ref_name}}
          ${{ vars.DOCKER_USERNAME }}/github-actions-app:v1
          ${{ vars.DOCKER_USERNAME }}/github-actions-app:${{ github.sha}}
          
         
