# this tell which type of your work file in git hub action

name: Hello-Second-Work-flow

on: push  

# this job : specific task do
jobs:

  greet: # job-1
    runs-on: ubuntu-latest # where my job run

    steps: # it steps to the command run on the job
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: say hello to git hub
        run: echo "Hello git hub this is Suraj"

      - name: display the date and time
        run: |
          echo " display the date and time: $(date)"

      - name: print the branch name
        run: |
          echo "Branch name is ${{ github.ref_name }}"

      - name: list files
        run: ls

      - name: check the version of the ubuntu:os
        run: cat /etc/os-release    
