name: Trigger on Pull Request

on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check code quality
        uses: actions/checkout@v4

      - name: say hello the user
        run: echo "this is from user"

      - name: PR check for the branch name
        run: |
          echo "PR branch name is ${{ github.ref_name }}"

