name: Trigger on Pull Request

on:
  
  pull_request:
    branches:
      - main
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check code quality
        uses: actions/checkout@v4

      - name: say hello the user
        run: echo "this is from user"

      - name: PR check for the branch name
        run: |
          echo "PR branch name is ${{ github.ref_name }}"
      - name: PR info 
        run: |
          echo "hello"
          echo "PR number is ${{ github.event.pull_request.number }}"
          echo "Source branch For PR ${{ github.head_ref }}"
          echo "Target branch for PR ${{ gitub.base_ref }}"
