name: Practice Secret

on: workflow_dispatch

jobs:
  practice_secret:
   runs-on: ubuntu-latest
   steps:
     - name: code check quality
       uses: actions/checkout@v5

     - name: verify the secret exists
       run: |
        echo "The secret set is: ${{ secrets.MY_SECRET_MESSAGE != ''}}"
        echo "good brother"
        echo "My secret is: $${ secrets.MY_SECRET_MESSAGE }}"
