name: Python Code Check

on:
    workflow_dispatch
    # push:
    #     branches:
    #         - main
env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    Syntax_check_for_python:
        runs-on: ubuntu-latest
        steps:
            - name: code check of repo
              uses: actions/checkout@v5

            - name: setup-python version(3.11)
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: update the pip and Install the dependencies
              run: |
                  python -m pip install --upgrade pip 
                  python -m pip install -r requirements.txt

            - name: display the name
              run: echo "hello brother"

            - name: check the syntax of python file
              run: flake8 app.py
