name: Suraj Secret

on: workflow_dispatch


jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print if secret exists
        run: |
         echo "The secret is set: ${{ secrets.MY_SECRET_MESSAGE != '' }}"
