name: SECRET CHECK

on: workflow_dispatch

jobs:
  SECRET:
   runs-on: ubuntu-latest
   steps:
     - name: code check
       uses: actions/checkout@v4
     - name: Secret exists
       if: ${{ secrets.MY_SECRET_MESSAGE != '' }}
       run: |
        echo "The secret set is: true"

     #- name: Check the secret is available 
       #run: |
        #echo "My secret is: $${{secrets.MY_SECRET_MESSAGE}}"
       #run: |
        #echo " The secret set is: true"
