name: Verify Secret

on: workflow_dispatch

jobs:
  test_secret:
   runs-on: ubuntu-latest
   steps:
   
     - name: code check
       uses: actions/checkout@v5
       env:
         Passowrd: ${{secrets.MY_SECRET_MESSAGE}}

     - name: SECRETS verify
       run: |
        echo "MY secret set: $(Password !== ' ')"
        eho "MY secret is: $Password"
        
